spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a802
    username: root
    url: jdbc:mysql://mysql-container:3306/hellsfood?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  devtools:
    livereload:
      enabled: true
  application:
    name: authService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: ERROR
        security: DEBUG
      apache:
        tiles: INFO
    root: INFO
  file:
    name: './BE_auth.log'
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 8010
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
springfox:
  documentation:
    swagger:
      use-model-v3: false
jwt:
  secret: IfYouLeftYourFoodYouWillEatYourRemainsInHell